### ISSUE TITLE
Package stemmer not 

### ISSUE THREAD

**Issue by Michael-E-Rose** [ytmytm/python-textmining#1]
It seems package stemmer is not automatically installed when I install textmining from PyPI.  I can't even find it for Python 3?

```
$ pip3 install textmining
Collecting textmining
  Downloading textmining-1.0.zip (1.9MB)
    100% |████████████████████████████████| 1.9MB 528kB/s 
Building wheels for collected packages: textmining
  Running setup.py bdist_wheel for textmining ... done
  Stored in directory: /root/.cache/pip/wheels/93/8f/53/f9267c41a454c092a6a0b9b87d7de96ac2b55a3163043ec5b3
Successfully built textmining
Installing collected packages: textmining
Successfully installed textmining-1.0
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textmining
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/textmining/__init__.py", line 2, in <module>
    import stemmer
ImportError: No module named 'stemmer'
```

**Comment by BenjaminLiuPenrose** [comment]
It's a known issue, you can follow advise here, https://stackoverflow.com/questions/15717752/python3-3-importerror-with-textmining-1-0

**Comment by BenjaminLiuPenrose** [comment]
another hacky way will be using this `import nltk.stem as stemmer` nltk implement the required class in stemmer as well
